{{- if .Values.services.webServer.createIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kebabcase-release-name" . }}-web-server-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: web-server
    app.kubernetes.io/component: ingress
{{ include "recommended-labels" . | indent 4 }}
  annotations:
{{ include "ingress-label" . | indent 4 }}
spec:
  rules:
  - host: {{ .Values.services.webServer.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "kebabcase-release-name" . }}-web-server
            port:
              number: {{- if .Values.services.webServer.useHttps -}}
                       {{ .Values.services.webServer.httpsPort }}
                     {{- else -}}
                       {{ .Values.services.webServer.httpPort }}
                     {{- end }}
{{- end }}